{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 진짜 완전 새롭게 다시 시작"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "MJCF Model Path: \n",
      "c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n"
     ]
    }
   ],
   "source": [
    "import gymnasium as gym\n",
    "import horcrux_terrain_v2\n",
    "from horcrux_terrain_v2.envs import PlaneJoyWorld\n",
    "import numpy as np\n",
    "\n",
    "from ray.tune.registry import register_env\n",
    "from ray.rllib.algorithms.sac import SACConfig"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "env_config = {\n",
    "    \"forward_reward_weight\": 6.5,\n",
    "    \"side_cost_weight\": 2.0,\n",
    "    \"unhealthy_max_steps\": 100,\n",
    "    \"healthy_reward\": 0.5,\n",
    "    \"healthy_roll_range\": (-35,35),\n",
    "    \"terminating_roll_range\": (-85,85),\n",
    "    \"rotation_norm_cost_weight\": 0.01,\n",
    "    \"rotation_orientation_cost_weight\": 1.2,\n",
    "    \"termination_reward\": 0,\n",
    "    \"gait_params\": (30, 30, 60, 60, 0),\n",
    "    \"use_friction_chg\": True,\n",
    "    \"joy_input_random\": True,\n",
    "}\n",
    "\n",
    "# JoyWorld\n",
    "register_env(\"joy-v1\", lambda env_config: PlaneJoyWorld(env_config))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-03-13 17:51:56,461\tWARNING algorithm_config.py:4703 -- You are running SAC on the new API stack! This is the new default behavior for this algorithm. If you don't want to use the new API stack, set `config.api_stack(enable_rl_module_and_learner=False,enable_env_runner_and_connector_v2=False)`. For a detailed migration guide, see here: https://docs.ray.io/en/master/rllib/new-api-stack-migration-guide.html\n",
      "2025-03-13 17:51:56,461\tWARNING sac.py:487 -- You are running SAC on the new API stack! This is the new default behavior for this algorithm. If you don't want to use the new API stack, set `config.api_stack(enable_rl_module_and_learner=False, enable_env_runner_and_connector_v2=False)`. For a detailed migration guide, see here: https://docs.ray.io/en/master/rllib/new-api-stack-migration-guide.html\n",
      "c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py:512: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "`UnifiedLogger` will be removed in Ray 2.7.\n",
      "  return UnifiedLogger(config, logdir, loggers=None)\n",
      "c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\tune\\logger\\unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "The `JsonLogger interface is deprecated in favor of the `ray.tune.json.JsonLoggerCallback` interface and will be removed in Ray 2.7.\n",
      "  self._loggers.append(cls(self.config, self.logdir, self.trial))\n",
      "c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\tune\\logger\\unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "The `CSVLogger interface is deprecated in favor of the `ray.tune.csv.CSVLoggerCallback` interface and will be removed in Ray 2.7.\n",
      "  self._loggers.append(cls(self.config, self.logdir, self.trial))\n",
      "c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\tune\\logger\\unified.py:53: RayDeprecationWarning: This API is deprecated and may be removed in future Ray releases. You could suppress this warning by setting env variable PYTHONWARNINGS=\"ignore::DeprecationWarning\"\n",
      "The `TBXLogger interface is deprecated in favor of the `ray.tune.tensorboardx.TBXLoggerCallback` interface and will be removed in Ray 2.7.\n",
      "  self._loggers.append(cls(self.config, self.logdir, self.trial))\n",
      "2025-03-13 17:51:59,424\tINFO worker.py:1832 -- Started a local Ray instance. View the dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265 \u001b[39m\u001b[22m\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m Exception raised in creation task: The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=32352, ip=127.0.0.1, actor_id=d80c73bc0c2524ec5a387e4f01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001B990129610>)\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m     return method(__ray_actor, *args, **kwargs)\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m     self.make_env()\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m     return method(self, *_args, **_kwargs)\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m     gym.make_vec(\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m     env = gym.vector.SyncVectorEnv(\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m           ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m     self.envs = [env_fn() for env_fn in env_fns]\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m                  ^^^^^^^^\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m     single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m     env = env_creator(**env_spec_kwargs)\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m     MujocoEnv.__init__(\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m     self.fullpath = expand_model_path(model_path)\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m   File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m     if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m        ^^^^^^^^^^^^^^^^^^^^^\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m AttributeError: 'EnvContext' object has no attribute 'startswith'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m MJCF Model Path: \n",
      "\u001b[36m(SingleAgentEnvRunner pid=32352)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=2924)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32216)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=19968)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=33936)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=31088)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=32616)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=30516)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=33968)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=14120)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=31876)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=27408)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=31720)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-03-13 17:52:08,867\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=32352, ip=127.0.0.1, actor_id=d80c73bc0c2524ec5a387e4f01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001B990129610>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 1 out of service.\n",
      "2025-03-13 17:52:08,868\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=2924, ip=127.0.0.1, actor_id=519105c3c78b08a32c28363601000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000002A8902ED670>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 2 out of service.\n",
      "2025-03-13 17:52:08,870\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=32216, ip=127.0.0.1, actor_id=3ce5c49262dab625928c92cd01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000002179001D640>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 3 out of service.\n",
      "2025-03-13 17:52:08,872\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=19968, ip=127.0.0.1, actor_id=cb176a21769cd8df56b29afb01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001F9167799D0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 4 out of service.\n",
      "2025-03-13 17:52:08,873\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=31088, ip=127.0.0.1, actor_id=323b0aeabcb9f7aee5202ffe01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001668FF498B0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 5 out of service.\n",
      "2025-03-13 17:52:08,873\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=33936, ip=127.0.0.1, actor_id=357dc9076503ad155ba1813a01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x00000219B40E9520>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 6 out of service.\n",
      "2025-03-13 17:52:08,876\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=32616, ip=127.0.0.1, actor_id=c9bf65edb49ef28dea91da2301000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x0000016B902813A0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 7 out of service.\n",
      "2025-03-13 17:52:08,876\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=30516, ip=127.0.0.1, actor_id=6efc871b0f358fd43e91092e01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x00000121100FD6A0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 8 out of service.\n",
      "2025-03-13 17:52:08,876\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=33968, ip=127.0.0.1, actor_id=51f4f4c950b59bab67f1312a01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000002880FF996D0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 9 out of service.\n",
      "2025-03-13 17:52:08,880\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=14120, ip=127.0.0.1, actor_id=3469c09996df7e6fddd66f4001000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001EB90131610>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 10 out of service.\n",
      "2025-03-13 17:52:08,880\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=31876, ip=127.0.0.1, actor_id=7a03ae3f0619e5bbc3256f5d01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001C89013D4F0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 11 out of service.\n",
      "2025-03-13 17:52:08,883\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=27408, ip=127.0.0.1, actor_id=7092110557590ea1b7d5c63f01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x00000279B3E19640>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 12 out of service.\n",
      "2025-03-13 17:52:08,885\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=31720, ip=127.0.0.1, actor_id=5706bdb0aed3479188e212bb01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001CF33FF9730>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 13 out of service.\n",
      "2025-03-13 17:52:08,886\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=21988, ip=127.0.0.1, actor_id=706f4b2222e80bac69570ee701000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x0000018C901D9700>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 14 out of service.\n",
      "2025-03-13 17:52:08,888\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=9732, ip=127.0.0.1, actor_id=1bc2d44f433a5883d4d455bf01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x0000025A0FFC9520>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 15 out of service.\n",
      "2025-03-13 17:52:08,889\tERROR actor_manager.py:833 -- Ray error (The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=2864, ip=127.0.0.1, actor_id=ee488e8baf484a9189a9adf401000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001628FF1D5E0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'), taking actor 16 out of service.\n",
      "2025-03-13 17:52:08,890\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=32352, ip=127.0.0.1, actor_id=d80c73bc0c2524ec5a387e4f01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001B990129610>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,890\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=2924, ip=127.0.0.1, actor_id=519105c3c78b08a32c28363601000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000002A8902ED670>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,891\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=32216, ip=127.0.0.1, actor_id=3ce5c49262dab625928c92cd01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000002179001D640>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,892\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=19968, ip=127.0.0.1, actor_id=cb176a21769cd8df56b29afb01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001F9167799D0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,892\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=31088, ip=127.0.0.1, actor_id=323b0aeabcb9f7aee5202ffe01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001668FF498B0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,893\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=33936, ip=127.0.0.1, actor_id=357dc9076503ad155ba1813a01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x00000219B40E9520>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,894\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=32616, ip=127.0.0.1, actor_id=c9bf65edb49ef28dea91da2301000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x0000016B902813A0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,894\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=30516, ip=127.0.0.1, actor_id=6efc871b0f358fd43e91092e01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x00000121100FD6A0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,896\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=33968, ip=127.0.0.1, actor_id=51f4f4c950b59bab67f1312a01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000002880FF996D0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,897\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=14120, ip=127.0.0.1, actor_id=3469c09996df7e6fddd66f4001000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001EB90131610>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,898\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=31876, ip=127.0.0.1, actor_id=7a03ae3f0619e5bbc3256f5d01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001C89013D4F0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,899\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=27408, ip=127.0.0.1, actor_id=7092110557590ea1b7d5c63f01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x00000279B3E19640>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,899\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=31720, ip=127.0.0.1, actor_id=5706bdb0aed3479188e212bb01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001CF33FF9730>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,899\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=21988, ip=127.0.0.1, actor_id=706f4b2222e80bac69570ee701000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x0000018C901D9700>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,901\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=9732, ip=127.0.0.1, actor_id=1bc2d44f433a5883d4d455bf01000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x0000025A0FFC9520>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n",
      "2025-03-13 17:52:08,901\tERROR env_runner_group.py:689 -- Validation of EnvRunner failed! Error=The actor died because of an error raised in its creation task, \u001b[36mray::SingleAgentEnvRunner.__init__()\u001b[39m (pid=2864, ip=127.0.0.1, actor_id=ee488e8baf484a9189a9adf401000000, repr=<ray.rllib.env.single_agent_env_runner.SingleAgentEnvRunner object at 0x000001628FF1D5E0>)\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1883, in ray._raylet.execute_task\n",
      "  File \"python\\\\ray\\\\_raylet.pyx\", line 1824, in ray._raylet.execute_task.function_executor\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\_private\\function_manager.py\", line 696, in actor_method_executor\n",
      "    return method(__ray_actor, *args, **kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 100, in __init__\n",
      "    self.make_env()\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\util\\tracing\\tracing_helper.py\", line 463, in _resume_span\n",
      "    return method(self, *_args, **_kwargs)\n",
      "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py\", line 654, in make_env\n",
      "    gym.make_vec(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 918, in make_vec\n",
      "    env = gym.vector.SyncVectorEnv(\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py\", line 86, in __init__\n",
      "    self.envs = [env_fn() for env_fn in env_fns]\n",
      "                 ^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 903, in create_single_env\n",
      "    single_env = make(env_spec, **env_spec_kwargs.copy())\n",
      "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py\", line 740, in make\n",
      "    env = env_creator(**env_spec_kwargs)\n",
      "          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"C:\\Users\\doore\\AppData\\Local\\Temp\\ipykernel_29044\\3867547534.py\", line 17, in <lambda>\n",
      "  File \"c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py\", line 141, in __init__\n",
      "    MujocoEnv.__init__(\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 73, in __init__\n",
      "    self.fullpath = expand_model_path(model_path)\n",
      "                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  File \"c:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py\", line 25, in expand_model_path\n",
      "    if model_path.startswith(\".\") or model_path.startswith(\"/\"):\n",
      "       ^^^^^^^^^^^^^^^^^^^^^\n",
      "AttributeError: 'EnvContext' object has no attribute 'startswith'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[36m(SingleAgentEnvRunner pid=21988)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=9732)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n",
      "\u001b[36m(SingleAgentEnvRunner pid=2864)\u001b[0m c:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\resources\\horcrux_plane.xml\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'EnvContext' object has no attribute 'startswith'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mAttributeError\u001b[39m                            Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[3]\u001b[39m\u001b[32m, line 13\u001b[39m\n\u001b[32m      1\u001b[39m config = (\n\u001b[32m      2\u001b[39m     SACConfig()\n\u001b[32m      3\u001b[39m     .environment(\u001b[33m\"\u001b[39m\u001b[33mjoy-v1\u001b[39m\u001b[33m\"\u001b[39m)\n\u001b[32m   (...)\u001b[39m\u001b[32m     10\u001b[39m     )\n\u001b[32m     11\u001b[39m )\n\u001b[32m     12\u001b[39m \u001b[38;5;66;03m# Build the SAC algo object from the config and run 1 training iteration.\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m13\u001b[39m algo = \u001b[43mconfig\u001b[49m\u001b[43m.\u001b[49m\u001b[43mbuild_algo\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     14\u001b[39m algo.train()\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\algorithms\\algorithm_config.py:958\u001b[39m, in \u001b[36mAlgorithmConfig.build_algo\u001b[39m\u001b[34m(self, env, logger_creator, use_copy)\u001b[39m\n\u001b[32m    955\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(\u001b[38;5;28mself\u001b[39m.algo_class, \u001b[38;5;28mstr\u001b[39m):\n\u001b[32m    956\u001b[39m     algo_class = get_trainable_cls(\u001b[38;5;28mself\u001b[39m.algo_class)\n\u001b[32m--> \u001b[39m\u001b[32m958\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43malgo_class\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    959\u001b[39m \u001b[43m    \u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mif\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mnot\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43muse_copy\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01melse\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mcopy\u001b[49m\u001b[43m.\u001b[49m\u001b[43mdeepcopy\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    960\u001b[39m \u001b[43m    \u001b[49m\u001b[43mlogger_creator\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mlogger_creator\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    961\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\algorithms\\sac\\sac.py:570\u001b[39m, in \u001b[36mSAC.__init__\u001b[39m\u001b[34m(self, *args, **kwargs)\u001b[39m\n\u001b[32m    568\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m__init__\u001b[39m(\u001b[38;5;28mself\u001b[39m, *args, **kwargs):\n\u001b[32m    569\u001b[39m     \u001b[38;5;28mself\u001b[39m._allow_unknown_subkeys += [\u001b[33m\"\u001b[39m\u001b[33mpolicy_model_config\u001b[39m\u001b[33m\"\u001b[39m, \u001b[33m\"\u001b[39m\u001b[33mq_model_config\u001b[39m\u001b[33m\"\u001b[39m]\n\u001b[32m--> \u001b[39m\u001b[32m570\u001b[39m     \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m.\u001b[49m\u001b[34;43m__init__\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py:528\u001b[39m, in \u001b[36mAlgorithm.__init__\u001b[39m\u001b[34m(self, config, env, logger_creator, **kwargs)\u001b[39m\n\u001b[32m    525\u001b[39m \u001b[38;5;66;03m# Evaluation EnvRunnerGroup and metrics last returned by `self.evaluate()`.\u001b[39;00m\n\u001b[32m    526\u001b[39m \u001b[38;5;28mself\u001b[39m.eval_env_runner_group: Optional[EnvRunnerGroup] = \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m528\u001b[39m \u001b[38;5;28;43msuper\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m.\u001b[49m\u001b[34;43m__init__\u001b[39;49m\u001b[43m(\u001b[49m\n\u001b[32m    529\u001b[39m \u001b[43m    \u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m=\u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    530\u001b[39m \u001b[43m    \u001b[49m\u001b[43mlogger_creator\u001b[49m\u001b[43m=\u001b[49m\u001b[43mlogger_creator\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    531\u001b[39m \u001b[43m    \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    532\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\tune\\trainable\\trainable.py:157\u001b[39m, in \u001b[36mTrainable.__init__\u001b[39m\u001b[34m(self, config, logger_creator, storage)\u001b[39m\n\u001b[32m    153\u001b[39m     logger.debug(\u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mStorageContext on the TRAINABLE:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{\u001b[39;00mstorage\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m\"\u001b[39m)\n\u001b[32m    155\u001b[39m \u001b[38;5;28mself\u001b[39m._open_logfiles(stdout_file, stderr_file)\n\u001b[32m--> \u001b[39m\u001b[32m157\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43msetup\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcopy\u001b[49m\u001b[43m.\u001b[49m\u001b[43mdeepcopy\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    158\u001b[39m setup_time = time.time() - \u001b[38;5;28mself\u001b[39m._start_time\n\u001b[32m    159\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m setup_time > SETUP_TIME_THRESHOLD:\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\algorithms\\algorithm.py:631\u001b[39m, in \u001b[36mAlgorithm.setup\u001b[39m\u001b[34m(self, config)\u001b[39m\n\u001b[32m    627\u001b[39m     \u001b[38;5;28mself\u001b[39m.offline_data = \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m    629\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28mself\u001b[39m.offline_data:\n\u001b[32m    630\u001b[39m     \u001b[38;5;66;03m# Create a set of env runner actors via a EnvRunnerGroup.\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m631\u001b[39m     \u001b[38;5;28mself\u001b[39m.env_runner_group = \u001b[43mEnvRunnerGroup\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    632\u001b[39m \u001b[43m        \u001b[49m\u001b[43menv_creator\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43menv_creator\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    633\u001b[39m \u001b[43m        \u001b[49m\u001b[43mvalidate_env\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mvalidate_env\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    634\u001b[39m \u001b[43m        \u001b[49m\u001b[43mdefault_policy_class\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mget_default_policy_class\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    635\u001b[39m \u001b[43m        \u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    636\u001b[39m \u001b[43m        \u001b[49m\u001b[43mlocal_env_runner\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[32m    637\u001b[39m \u001b[43m        \u001b[49m\u001b[43mlogdir\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mlogdir\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    638\u001b[39m \u001b[43m        \u001b[49m\u001b[43mtune_trial_id\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mtrial_id\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    639\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    641\u001b[39m \u001b[38;5;66;03m# Compile, validate, and freeze an evaluation config.\u001b[39;00m\n\u001b[32m    642\u001b[39m \u001b[38;5;28mself\u001b[39m.evaluation_config = \u001b[38;5;28mself\u001b[39m.config.get_evaluation_config_object()\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\env_runner_group.py:198\u001b[39m, in \u001b[36mEnvRunnerGroup.__init__\u001b[39m\u001b[34m(self, env_creator, validate_env, default_policy_class, config, local_env_runner, logdir, _setup, tune_trial_id, pg_offset, num_env_runners, num_workers, local_worker)\u001b[39m\n\u001b[32m    196\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m _setup:\n\u001b[32m    197\u001b[39m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m198\u001b[39m         \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_setup\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    199\u001b[39m \u001b[43m            \u001b[49m\u001b[43mvalidate_env\u001b[49m\u001b[43m=\u001b[49m\u001b[43mvalidate_env\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    200\u001b[39m \u001b[43m            \u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m=\u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    201\u001b[39m \u001b[43m            \u001b[49m\u001b[43mnum_env_runners\u001b[49m\u001b[43m=\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    202\u001b[39m \u001b[43m                \u001b[49m\u001b[43mnum_env_runners\u001b[49m\n\u001b[32m    203\u001b[39m \u001b[43m                \u001b[49m\u001b[38;5;28;43;01mif\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mnum_env_runners\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mis\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;129;43;01mnot\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\n\u001b[32m    204\u001b[39m \u001b[43m                \u001b[49m\u001b[38;5;28;43;01melse\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m.\u001b[49m\u001b[43mnum_env_runners\u001b[49m\n\u001b[32m    205\u001b[39m \u001b[43m            \u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    206\u001b[39m \u001b[43m            \u001b[49m\u001b[43mlocal_env_runner\u001b[49m\u001b[43m=\u001b[49m\u001b[43mlocal_env_runner\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    207\u001b[39m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    208\u001b[39m     \u001b[38;5;66;03m# EnvRunnerGroup creation possibly fails, if some (remote) workers cannot\u001b[39;00m\n\u001b[32m    209\u001b[39m     \u001b[38;5;66;03m# be initialized properly (due to some errors in the EnvRunners's\u001b[39;00m\n\u001b[32m    210\u001b[39m     \u001b[38;5;66;03m# constructor).\u001b[39;00m\n\u001b[32m    211\u001b[39m     \u001b[38;5;28;01mexcept\u001b[39;00m RayActorError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m    212\u001b[39m         \u001b[38;5;66;03m# In case of an actor (remote worker) init failure, the remote worker\u001b[39;00m\n\u001b[32m    213\u001b[39m         \u001b[38;5;66;03m# may still exist and will be accessible, however, e.g. calling\u001b[39;00m\n\u001b[32m    214\u001b[39m         \u001b[38;5;66;03m# its `sample.remote()` would result in strange \"property not found\"\u001b[39;00m\n\u001b[32m    215\u001b[39m         \u001b[38;5;66;03m# errors.\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\env_runner_group.py:293\u001b[39m, in \u001b[36mEnvRunnerGroup._setup\u001b[39m\u001b[34m(self, validate_env, config, num_env_runners, local_env_runner)\u001b[39m\n\u001b[32m    291\u001b[39m \u001b[38;5;66;03m# Create a local worker, if needed.\u001b[39;00m\n\u001b[32m    292\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m local_env_runner:\n\u001b[32m--> \u001b[39m\u001b[32m293\u001b[39m     \u001b[38;5;28mself\u001b[39m._local_env_runner = \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_make_worker\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    294\u001b[39m \u001b[43m        \u001b[49m\u001b[43menv_creator\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_env_creator\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    295\u001b[39m \u001b[43m        \u001b[49m\u001b[43mvalidate_env\u001b[49m\u001b[43m=\u001b[49m\u001b[43mvalidate_env\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    296\u001b[39m \u001b[43m        \u001b[49m\u001b[43mworker_index\u001b[49m\u001b[43m=\u001b[49m\u001b[32;43m0\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m    297\u001b[39m \u001b[43m        \u001b[49m\u001b[43mnum_workers\u001b[49m\u001b[43m=\u001b[49m\u001b[43mnum_env_runners\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    298\u001b[39m \u001b[43m        \u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43m_local_config\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    299\u001b[39m \u001b[43m        \u001b[49m\u001b[43mspaces\u001b[49m\u001b[43m=\u001b[49m\u001b[43mspaces\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    300\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\env_runner_group.py:1207\u001b[39m, in \u001b[36mEnvRunnerGroup._make_worker\u001b[39m\u001b[34m(self, env_creator, validate_env, worker_index, num_workers, recreated_worker, config, spaces)\u001b[39m\n\u001b[32m   1192\u001b[39m kwargs = \u001b[38;5;28mdict\u001b[39m(\n\u001b[32m   1193\u001b[39m     env_creator=env_creator,\n\u001b[32m   1194\u001b[39m     validate_env=validate_env,\n\u001b[32m   (...)\u001b[39m\u001b[32m   1203\u001b[39m     tune_trial_id=\u001b[38;5;28mself\u001b[39m._tune_trial_id,\n\u001b[32m   1204\u001b[39m )\n\u001b[32m   1206\u001b[39m \u001b[38;5;28;01mif\u001b[39;00m worker_index == \u001b[32m0\u001b[39m:\n\u001b[32m-> \u001b[39m\u001b[32m1207\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43menv_runner_cls\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m   1209\u001b[39m pg_bundle_idx = (\n\u001b[32m   1210\u001b[39m     -\u001b[32m1\u001b[39m\n\u001b[32m   1211\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m ray.util.get_current_placement_group() \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m   1212\u001b[39m     \u001b[38;5;28;01melse\u001b[39;00m \u001b[38;5;28mself\u001b[39m._pg_offset + worker_index\n\u001b[32m   1213\u001b[39m )\n\u001b[32m   1214\u001b[39m \u001b[38;5;28;01mreturn\u001b[39;00m (\n\u001b[32m   1215\u001b[39m     ray.remote(**\u001b[38;5;28mself\u001b[39m._remote_args)(\u001b[38;5;28mself\u001b[39m.env_runner_cls)\n\u001b[32m   1216\u001b[39m     .options(placement_group_bundle_index=pg_bundle_idx)\n\u001b[32m   1217\u001b[39m     .remote(**kwargs)\n\u001b[32m   1218\u001b[39m )\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py:100\u001b[39m, in \u001b[36mSingleAgentEnvRunner.__init__\u001b[39m\u001b[34m(self, config, **kwargs)\u001b[39m\n\u001b[32m     98\u001b[39m \u001b[38;5;28mself\u001b[39m.env: Optional[gym.vector.VectorEnvWrapper] = \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m     99\u001b[39m \u001b[38;5;28mself\u001b[39m.num_envs: \u001b[38;5;28mint\u001b[39m = \u001b[32m0\u001b[39m\n\u001b[32m--> \u001b[39m\u001b[32m100\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mmake_env\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    102\u001b[39m \u001b[38;5;66;03m# Create the env-to-module connector pipeline.\u001b[39;00m\n\u001b[32m    103\u001b[39m \u001b[38;5;28mself\u001b[39m._env_to_module = \u001b[38;5;28mself\u001b[39m.config.build_env_to_module_connector(\n\u001b[32m    104\u001b[39m     \u001b[38;5;28mself\u001b[39m.env, device=\u001b[38;5;28mself\u001b[39m._device\n\u001b[32m    105\u001b[39m )\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\ray\\rllib\\env\\single_agent_env_runner.py:654\u001b[39m, in \u001b[36mSingleAgentEnvRunner.make_env\u001b[39m\u001b[34m(self)\u001b[39m\n\u001b[32m    650\u001b[39m gym.register(\u001b[33m\"\u001b[39m\u001b[33mrllib-single-agent-env-v0\u001b[39m\u001b[33m\"\u001b[39m, entry_point=entry_point)\n\u001b[32m    651\u001b[39m vectorize_mode = \u001b[38;5;28mself\u001b[39m.config.gym_env_vectorize_mode\n\u001b[32m    653\u001b[39m \u001b[38;5;28mself\u001b[39m.env = DictInfoToList(\n\u001b[32m--> \u001b[39m\u001b[32m654\u001b[39m     \u001b[43mgym\u001b[49m\u001b[43m.\u001b[49m\u001b[43mmake_vec\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    655\u001b[39m \u001b[43m        \u001b[49m\u001b[33;43m\"\u001b[39;49m\u001b[33;43mrllib-single-agent-env-v0\u001b[39;49m\u001b[33;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m    656\u001b[39m \u001b[43m        \u001b[49m\u001b[43mnum_envs\u001b[49m\u001b[43m=\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m.\u001b[49m\u001b[43mconfig\u001b[49m\u001b[43m.\u001b[49m\u001b[43mnum_envs_per_env_runner\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    657\u001b[39m \u001b[43m        \u001b[49m\u001b[43mvectorization_mode\u001b[49m\u001b[43m=\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    658\u001b[39m \u001b[43m            \u001b[49m\u001b[43mvectorize_mode\u001b[49m\n\u001b[32m    659\u001b[39m \u001b[43m            \u001b[49m\u001b[38;5;28;43;01mif\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43misinstance\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mvectorize_mode\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mgym\u001b[49m\u001b[43m.\u001b[49m\u001b[43menvs\u001b[49m\u001b[43m.\u001b[49m\u001b[43mregistration\u001b[49m\u001b[43m.\u001b[49m\u001b[43mVectorizeMode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    660\u001b[39m \u001b[43m            \u001b[49m\u001b[38;5;28;43;01melse\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43mgym\u001b[49m\u001b[43m.\u001b[49m\u001b[43menvs\u001b[49m\u001b[43m.\u001b[49m\u001b[43mregistration\u001b[49m\u001b[43m.\u001b[49m\u001b[43mVectorizeMode\u001b[49m\u001b[43m(\u001b[49m\u001b[43mvectorize_mode\u001b[49m\u001b[43m.\u001b[49m\u001b[43mlower\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    661\u001b[39m \u001b[43m        \u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    662\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    663\u001b[39m )\n\u001b[32m    665\u001b[39m \u001b[38;5;28mself\u001b[39m.num_envs: \u001b[38;5;28mint\u001b[39m = \u001b[38;5;28mself\u001b[39m.env.num_envs\n\u001b[32m    666\u001b[39m \u001b[38;5;28;01massert\u001b[39;00m \u001b[38;5;28mself\u001b[39m.num_envs == \u001b[38;5;28mself\u001b[39m.config.num_envs_per_env_runner\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py:918\u001b[39m, in \u001b[36mmake_vec\u001b[39m\u001b[34m(id, num_envs, vectorization_mode, vector_kwargs, wrappers, **kwargs)\u001b[39m\n\u001b[32m    913\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m env_spec.entry_point \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m    914\u001b[39m         \u001b[38;5;28;01mraise\u001b[39;00m error.Error(\n\u001b[32m    915\u001b[39m             \u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mCannot create vectorized environment for \u001b[39m\u001b[38;5;132;01m{\u001b[39;00menv_spec.id\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m because it doesn\u001b[39m\u001b[33m'\u001b[39m\u001b[33mt have an entry point defined.\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    916\u001b[39m         )\n\u001b[32m--> \u001b[39m\u001b[32m918\u001b[39m     env = \u001b[43mgym\u001b[49m\u001b[43m.\u001b[49m\u001b[43mvector\u001b[49m\u001b[43m.\u001b[49m\u001b[43mSyncVectorEnv\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m    919\u001b[39m \u001b[43m        \u001b[49m\u001b[43menv_fns\u001b[49m\u001b[43m=\u001b[49m\u001b[43m(\u001b[49m\u001b[43mcreate_single_env\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mfor\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[43m_\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;129;43;01min\u001b[39;49;00m\u001b[43m \u001b[49m\u001b[38;5;28;43mrange\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mnum_envs\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    920\u001b[39m \u001b[43m        \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mvector_kwargs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    921\u001b[39m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    922\u001b[39m \u001b[38;5;28;01melif\u001b[39;00m vectorization_mode == VectorizeMode.ASYNC:\n\u001b[32m    923\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m env_spec.entry_point \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\vector\\sync_vector_env.py:86\u001b[39m, in \u001b[36mSyncVectorEnv.__init__\u001b[39m\u001b[34m(self, env_fns, copy, observation_mode)\u001b[39m\n\u001b[32m     83\u001b[39m \u001b[38;5;28mself\u001b[39m.observation_mode = observation_mode\n\u001b[32m     85\u001b[39m \u001b[38;5;66;03m# Initialise all sub-environments\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m86\u001b[39m \u001b[38;5;28mself\u001b[39m.envs = [\u001b[43menv_fn\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m \u001b[38;5;28;01mfor\u001b[39;00m env_fn \u001b[38;5;129;01min\u001b[39;00m env_fns]\n\u001b[32m     88\u001b[39m \u001b[38;5;66;03m# Define core attributes using the sub-environments\u001b[39;00m\n\u001b[32m     89\u001b[39m \u001b[38;5;66;03m# As we support `make_vec(spec)` then we can't include a `spec = self.envs[0].spec` as this doesn't guarantee we can actual recreate the vector env.\u001b[39;00m\n\u001b[32m     90\u001b[39m \u001b[38;5;28mself\u001b[39m.num_envs = \u001b[38;5;28mlen\u001b[39m(\u001b[38;5;28mself\u001b[39m.envs)\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py:903\u001b[39m, in \u001b[36mmake_vec.<locals>.create_single_env\u001b[39m\u001b[34m()\u001b[39m\n\u001b[32m    902\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mcreate_single_env\u001b[39m() -> Env:\n\u001b[32m--> \u001b[39m\u001b[32m903\u001b[39m     single_env = \u001b[43mmake\u001b[49m\u001b[43m(\u001b[49m\u001b[43menv_spec\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43menv_spec_kwargs\u001b[49m\u001b[43m.\u001b[49m\u001b[43mcopy\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    905\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m wrappers \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[32m    906\u001b[39m         \u001b[38;5;28;01mreturn\u001b[39;00m single_env\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\registration.py:740\u001b[39m, in \u001b[36mmake\u001b[39m\u001b[34m(id, max_episode_steps, disable_env_checker, **kwargs)\u001b[39m\n\u001b[32m    734\u001b[39m         logger.warn(\n\u001b[32m    735\u001b[39m             \u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mThe environment is being initialised with render_mode=\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mrender_mode\u001b[38;5;132;01m!r}\u001b[39;00m\u001b[33m \u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    736\u001b[39m             \u001b[33mf\u001b[39m\u001b[33m\"\u001b[39m\u001b[33mthat is not in the possible render_modes (\u001b[39m\u001b[38;5;132;01m{\u001b[39;00mrender_modes\u001b[38;5;132;01m}\u001b[39;00m\u001b[33m).\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m    737\u001b[39m         )\n\u001b[32m    739\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m--> \u001b[39m\u001b[32m740\u001b[39m     env = \u001b[43menv_creator\u001b[49m\u001b[43m(\u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43menv_spec_kwargs\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    741\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m    742\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m (\n\u001b[32m    743\u001b[39m         \u001b[38;5;28mstr\u001b[39m(e).find(\u001b[33m\"\u001b[39m\u001b[33mgot an unexpected keyword argument \u001b[39m\u001b[33m'\u001b[39m\u001b[33mrender_mode\u001b[39m\u001b[33m'\u001b[39m\u001b[33m\"\u001b[39m) >= \u001b[32m0\u001b[39m\n\u001b[32m    744\u001b[39m         \u001b[38;5;129;01mand\u001b[39;00m apply_human_rendering\n\u001b[32m    745\u001b[39m     ):\n",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[2]\u001b[39m\u001b[32m, line 17\u001b[39m, in \u001b[36m<lambda>\u001b[39m\u001b[34m(env_config)\u001b[39m\n\u001b[32m      1\u001b[39m env_config = {\n\u001b[32m      2\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33mforward_reward_weight\u001b[39m\u001b[33m\"\u001b[39m: \u001b[32m6.5\u001b[39m,\n\u001b[32m      3\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33mside_cost_weight\u001b[39m\u001b[33m\"\u001b[39m: \u001b[32m2.0\u001b[39m,\n\u001b[32m   (...)\u001b[39m\u001b[32m     13\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33mjoy_input_random\u001b[39m\u001b[33m\"\u001b[39m: \u001b[38;5;28;01mTrue\u001b[39;00m,\n\u001b[32m     14\u001b[39m }\n\u001b[32m     16\u001b[39m \u001b[38;5;66;03m# JoyWorld\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m17\u001b[39m register_env(\u001b[33m\"\u001b[39m\u001b[33mjoy-v1\u001b[39m\u001b[33m\"\u001b[39m, \u001b[38;5;28;01mlambda\u001b[39;00m env_config: \u001b[43mPlaneJoyWorld\u001b[49m\u001b[43m(\u001b[49m\u001b[43menv_config\u001b[49m\u001b[43m)\u001b[49m)\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\users\\doore\\documents\\project\\snake_rl\\gd_tor\\learning\\horcrux_terrain_v2\\horcrux_terrain_v2\\envs\\plane_v2.py:141\u001b[39m, in \u001b[36mPlaneJoyWorld.__init__\u001b[39m\u001b[34m(self, model_path, frame_skip, default_camera_config, forward_reward_weight, termination_reward, side_cost_weight, ctrl_cost_weight, rotation_norm_cost_weight, rotation_orientation_cost_weight, unhealthy_cost_weight, healthy_reward, main_body, render_camera_name, terminate_when_unhealthy, unhealthy_max_steps, healthy_roll_range, terminating_roll_range, contact_force_range, reset_noise_scale, use_gait, use_friction_chg, joy_input_random, joy_input, gait_params, **kwargs)\u001b[39m\n\u001b[32m    137\u001b[39m _period = \u001b[38;5;28mint\u001b[39m(np.ceil((_temporal_param) / (\u001b[32m2\u001b[39m * np.pi))) * \u001b[32m2\u001b[39m\n\u001b[32m    138\u001b[39m \u001b[38;5;28mself\u001b[39m._mov_mean = MovingAverageFilter3D(window_size=_period)\n\u001b[32m--> \u001b[39m\u001b[32m141\u001b[39m \u001b[43mMujocoEnv\u001b[49m\u001b[43m.\u001b[49m\u001b[34;43m__init__\u001b[39;49m\u001b[43m(\u001b[49m\n\u001b[32m    142\u001b[39m \u001b[43m        \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m    143\u001b[39m \u001b[43m        \u001b[49m\u001b[43mmodel_path\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    144\u001b[39m \u001b[43m        \u001b[49m\u001b[43mframe_skip\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    145\u001b[39m \u001b[43m        \u001b[49m\u001b[43mwidth\u001b[49m\u001b[43m=\u001b[49m\u001b[32;43m1280\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m    146\u001b[39m \u001b[43m        \u001b[49m\u001b[43mheight\u001b[49m\u001b[43m=\u001b[49m\u001b[32;43m720\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m    147\u001b[39m \u001b[43m        \u001b[49m\u001b[43mobservation_space\u001b[49m\u001b[43m \u001b[49m\u001b[43m=\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;66;43;03m# define later\u001b[39;49;00m\n\u001b[32m    148\u001b[39m \u001b[43m        \u001b[49m\u001b[43mdefault_camera_config\u001b[49m\u001b[43m \u001b[49m\u001b[43m=\u001b[49m\u001b[43m \u001b[49m\u001b[43mdefault_camera_config\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    149\u001b[39m \u001b[43m        \u001b[49m\u001b[43mcamera_name\u001b[49m\u001b[43m \u001b[49m\u001b[43m=\u001b[49m\u001b[43m \u001b[49m\u001b[43mrender_camera_name\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    150\u001b[39m \u001b[43m        \u001b[49m\u001b[43m*\u001b[49m\u001b[43m*\u001b[49m\u001b[43mkwargs\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m    151\u001b[39m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m    153\u001b[39m \u001b[38;5;28mself\u001b[39m.metadata = {\n\u001b[32m    154\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33mrender_modes\u001b[39m\u001b[33m\"\u001b[39m: [\n\u001b[32m    155\u001b[39m         \u001b[33m\"\u001b[39m\u001b[33mhuman\u001b[39m\u001b[33m\"\u001b[39m,\n\u001b[32m   (...)\u001b[39m\u001b[32m    159\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33mrender_fps\u001b[39m\u001b[33m\"\u001b[39m: \u001b[38;5;28mint\u001b[39m(np.round(\u001b[32m1.0\u001b[39m / \u001b[38;5;28mself\u001b[39m.dt)),\n\u001b[32m    160\u001b[39m }\n\u001b[32m    162\u001b[39m obs_size = \u001b[38;5;28mself\u001b[39m.data.sensordata.size + \u001b[32m14\u001b[39m + \u001b[32m3\u001b[39m \u001b[38;5;66;03m## Motion vector + Joy input\u001b[39;00m\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py:73\u001b[39m, in \u001b[36mMujocoEnv.__init__\u001b[39m\u001b[34m(self, model_path, frame_skip, observation_space, render_mode, width, height, camera_id, camera_name, default_camera_config, max_geom, visual_options)\u001b[39m\n\u001b[32m     40\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34m__init__\u001b[39m(\n\u001b[32m     41\u001b[39m     \u001b[38;5;28mself\u001b[39m,\n\u001b[32m     42\u001b[39m     model_path: \u001b[38;5;28mstr\u001b[39m,\n\u001b[32m   (...)\u001b[39m\u001b[32m     52\u001b[39m     visual_options: Dict[\u001b[38;5;28mint\u001b[39m, \u001b[38;5;28mbool\u001b[39m] = {},\n\u001b[32m     53\u001b[39m ):\n\u001b[32m     54\u001b[39m \u001b[38;5;250m    \u001b[39m\u001b[33;03m\"\"\"Base abstract class for mujoco based environments.\u001b[39;00m\n\u001b[32m     55\u001b[39m \n\u001b[32m     56\u001b[39m \u001b[33;03m    Args:\u001b[39;00m\n\u001b[32m   (...)\u001b[39m\u001b[32m     71\u001b[39m \u001b[33;03m        error.DependencyNotInstalled: When `mujoco` is not installed.\u001b[39;00m\n\u001b[32m     72\u001b[39m \u001b[33;03m    \"\"\"\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m73\u001b[39m     \u001b[38;5;28mself\u001b[39m.fullpath = \u001b[43mexpand_model_path\u001b[49m\u001b[43m(\u001b[49m\u001b[43mmodel_path\u001b[49m\u001b[43m)\u001b[49m\n\u001b[32m     75\u001b[39m     \u001b[38;5;28mself\u001b[39m.width = width\n\u001b[32m     76\u001b[39m     \u001b[38;5;28mself\u001b[39m.height = height\n",
      "\u001b[36mFile \u001b[39m\u001b[32mc:\\Users\\doore\\anaconda3\\envs\\gd\\Lib\\site-packages\\gymnasium\\envs\\mujoco\\mujoco_env.py:25\u001b[39m, in \u001b[36mexpand_model_path\u001b[39m\u001b[34m(model_path)\u001b[39m\n\u001b[32m     23\u001b[39m \u001b[38;5;28;01mdef\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34mexpand_model_path\u001b[39m(model_path: \u001b[38;5;28mstr\u001b[39m) -> \u001b[38;5;28mstr\u001b[39m:\n\u001b[32m     24\u001b[39m \u001b[38;5;250m    \u001b[39m\u001b[33;03m\"\"\"Expands the `model_path` to a full path if it starts with '~' or '.' or '/'.\"\"\"\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m25\u001b[39m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[43mmodel_path\u001b[49m\u001b[43m.\u001b[49m\u001b[43mstartswith\u001b[49m(\u001b[33m\"\u001b[39m\u001b[33m.\u001b[39m\u001b[33m\"\u001b[39m) \u001b[38;5;129;01mor\u001b[39;00m model_path.startswith(\u001b[33m\"\u001b[39m\u001b[33m/\u001b[39m\u001b[33m\"\u001b[39m):\n\u001b[32m     26\u001b[39m         fullpath = model_path\n\u001b[32m     27\u001b[39m     \u001b[38;5;28;01melif\u001b[39;00m model_path.startswith(\u001b[33m\"\u001b[39m\u001b[33m~\u001b[39m\u001b[33m\"\u001b[39m):\n",
      "\u001b[31mAttributeError\u001b[39m: 'EnvContext' object has no attribute 'startswith'"
     ]
    }
   ],
   "source": [
    "config = (\n",
    "    SACConfig()\n",
    "    .environment(\"joy-v1\")\n",
    "    .env_runners(num_env_runners=1)\n",
    "    .training(\n",
    "        gamma=0.9,\n",
    "        actor_lr=0.001,\n",
    "        critic_lr=0.002,\n",
    "        train_batch_size_per_learner=256,\n",
    "    )\n",
    ")\n",
    "# Build the SAC algo object from the config and run 1 training iteration.\n",
    "algo = config.build_algo()\n",
    "algo.train()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "gd",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
